import io
import json
import zipfile


PRISMA_TYPE_MAP = {
    "text": "String", "textarea": "String", "number": "Float",
    "email": "String", "date": "DateTime", "select": "String",
    "checkbox": "Boolean", "url": "String",
}


def _to_prisma_type(field_type: str) -> str:
    return PRISMA_TYPE_MAP.get(field_type, "String")


def generate_app_zip(app: dict, repo_name: str, include_seed: bool) -> bytes:
    config = app["config"] if isinstance(app["config"], dict) else json.loads(app["config"])
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        prefix = f"{repo_name}/"

        # --- prisma/schema.prisma ---
        models = []
        for table in config.get("tables", []):
            model_name = table["label"].replace(" ", "")
            fields = "\n".join(
                f"  {f['name']}  {_to_prisma_type(f['type'])}{'?' if not f.get('required') else ''}"
                for f in table["fields"]
            )
            models.append(
                f"model {model_name} {{\n"
                f"  id        String   @id @default(cuid())\n"
                f"{fields}\n"
                f"  createdAt DateTime @default(now())\n"
                f"  updatedAt DateTime @updatedAt\n"
                f"}}"
            )

        schema_content = (
            "generator client {\n  provider = \"prisma-client-js\"\n}\n\n"
            "datasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\n"
            + "\n\n".join(models)
        )
        zf.writestr(f"{prefix}prisma/schema.prisma", schema_content)

        # --- API routes per table ---
        for table in config.get("tables", []):
            tname = table["name"]
            route = f"""import {{ NextResponse }} from 'next/server'
import prisma from '@/lib/db'

export async function GET() {{
  const records = await prisma.{tname}.findMany({{ orderBy: {{ createdAt: 'desc' }} }})
  return NextResponse.json(records)
}}

export async function POST(req: Request) {{
  const body = await req.json()
  const record = await prisma.{tname}.create({{ data: body }})
  return NextResponse.json(record, {{ status: 201 }})
}}
"""
            id_route = f"""import {{ NextResponse }} from 'next/server'
import prisma from '@/lib/db'

export async function PUT(req: Request, {{ params }}: {{ params: {{ id: string }} }}) {{
  const body = await req.json()
  const record = await prisma.{tname}.update({{ where: {{ id: params.id }}, data: body }})
  return NextResponse.json(record)
}}

export async function DELETE(_: Request, {{ params }}: {{ params: {{ id: string }} }}) {{
  await prisma.{tname}.delete({{ where: {{ id: params.id }} }})
  return NextResponse.json({{ success: true }})
}}
"""
            zf.writestr(f"{prefix}app/api/{tname}/route.ts", route)
            zf.writestr(f"{prefix}app/api/{tname}/[id]/route.ts", id_route)

        # --- lib/db.ts ---
        zf.writestr(f"{prefix}lib/db.ts", """import { PrismaClient } from '@prisma/client'
const g = global as any
export const prisma: PrismaClient = g.prisma ?? new PrismaClient()
if (process.env.NODE_ENV !== 'production') g.prisma = prisma
export default prisma
""")

        # --- .env.example ---
        zf.writestr(f"{prefix}.env.example", 'DATABASE_URL="postgresql://..."\nNEXTAUTH_SECRET="your-secret"\n')

        # --- README ---
        tables_list = "\n".join(
            f"- **{t['label']}**: {', '.join(f['label'] for f in t['fields'])}"
            for t in config.get("tables", [])
        )
        readme = f"""# {config.get('appName', repo_name)}

{config.get('description', 'Generated by ForgeAI')}

## Setup

```bash
npm install
cp .env.example .env
npx prisma migrate dev --name init
npm run dev
```

## Tables
{tables_list}

Generated by ForgeAI.
"""
        zf.writestr(f"{prefix}README.md", readme)

        # --- package.json ---
        pkg = {
            "name": repo_name.lower(),
            "version": "0.1.0",
            "scripts": {"dev": "next dev", "build": "next build", "start": "next start"},
            "dependencies": {"next": "^14.0.0", "react": "^18.0.0", "react-dom": "^18.0.0", "@prisma/client": "^5.0.0"},
            "devDependencies": {"prisma": "^5.0.0", "typescript": "^5.0.0"},
        }
        zf.writestr(f"{prefix}package.json", json.dumps(pkg, indent=2))

        # --- seed (optional) ---
        if include_seed:
            seed_blocks = []
            for table in config.get("tables", []):
                tname = table["name"]
                samples = []
                for i in range(5):
                    row = {}
                    for f in table["fields"]:
                        if f["type"] == "number":
                            row[f["name"]] = i + 1
                        elif f["type"] == "checkbox":
                            row[f["name"]] = False
                        elif f["type"] == "select":
                            row[f["name"]] = f.get("options", [""])[0]
                        else:
                            row[f["name"]] = f"Sample {f['label']} {i+1}"
                    samples.append(json.dumps(row))
                seed_blocks.append(
                    f"await prisma.{tname}.createMany({{ data: [{', '.join(samples)}], skipDuplicates: true }})"
                )
            seed_content = (
                "import { PrismaClient } from '@prisma/client'\n"
                "const prisma = new PrismaClient()\n"
                "async function main() {\n  "
                + "\n  ".join(seed_blocks)
                + "\n}\nmain().catch(console.error).finally(() => prisma.$disconnect())\n"
            )
            zf.writestr(f"{prefix}prisma/seed.ts", seed_content)

    buf.seek(0)
    return buf.read()
